/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finals.finalvoting;

import DataFiles.CandidateAccessObject;
import DataFiles.LocationHandler;
import DataFiles.UserAccessObject;
import DataFiles.UserTransferObject;
import DataFiles.VoteAccessObject;
import DataFiles.VoteTransferObject;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author REYMARK
 */
public class VoterDashboard extends javax.swing.JFrame {
    private static UserTransferObject user;
    /**
     * Creates new form VoterDashboard
     * @param user
     */
    public VoterDashboard(UserTransferObject user) {
        initComponents();
        
        // Voter's Card/Dashboard display
        VoterDashboard.user = user;
        votersIDValueLabel.setText(String.valueOf(user.getUserID()));
        registrationDateValueLabel.setText(String.valueOf(user.getRegistrationDate()));
        firstnameValueLabel.setText(user.getFirstname());
        lastnameValueLabel.setText(user.getLastname());
        emailValueLabel.setText(user.getEmail());
        ageValueLabel.setText(String.valueOf(computeAge(user)));
        genderValueLabel.setText(user.getGender());
        civilStatusValueLabel.setText(user.getStatus());
        municipalityValueLabel.setText(user.getMunicipality());
        barangayValueLabel.setText(user.getBarangay());
        passwordValueLabel.setText(user.getPassword());
        
        // Assigning items in each poll's ComboBox
        CandidateAccessObject accessObject = new CandidateAccessObject();
        accessObject.populateCandidates(presidentCombox, 1);
        accessObject.populateCandidates(vicePresidentCombox, 2);
        accessObject.populateCandidates(secretaryCombox, 3);
        accessObject.populateCandidates(treasurerCombox, 4);
        accessObject.populateCandidates(auditorCombox, 5);
        accessObject.populateCandidates(pioMaleCombox, 6);
        accessObject.populateCandidates(pioFemaleCombox, 7);
        accessObject.populateCandidates(representativeCombox, 8);
        
        VoteAccessObject voteAccessObject = new VoteAccessObject();
        if(voteAccessObject.isEligible(user.getUserID())){
            voteNowButton.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        castVotesDialog = new javax.swing.JDialog();
        castVotesPanel = new javax.swing.JPanel();
        castPresidentLabel = new javax.swing.JLabel();
        presidentCombox = new javax.swing.JComboBox<>();
        castVicePresidentLabel = new javax.swing.JLabel();
        castSecretaryLabel = new javax.swing.JLabel();
        castTreasurerLabel = new javax.swing.JLabel();
        castPIOMale = new javax.swing.JLabel();
        castAuditorLabel = new javax.swing.JLabel();
        castPIOFemale = new javax.swing.JLabel();
        castRepresentative = new javax.swing.JLabel();
        vicePresidentCombox = new javax.swing.JComboBox<>();
        secretaryCombox = new javax.swing.JComboBox<>();
        treasurerCombox = new javax.swing.JComboBox<>();
        auditorCombox = new javax.swing.JComboBox<>();
        pioMaleCombox = new javax.swing.JComboBox<>();
        pioFemaleCombox = new javax.swing.JComboBox<>();
        representativeCombox = new javax.swing.JComboBox<>();
        castMyVoteButton = new javax.swing.JButton();
        clearFieldButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        votersMainPanel = new javax.swing.JPanel();
        votersDetailsPanel = new javax.swing.JPanel();
        voterPhotoDashboard = new javax.swing.JLabel();
        votersIDLabel = new javax.swing.JLabel();
        votersIDValueLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        firstnameValueLabel = new javax.swing.JLabel();
        lastnameValueLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        ageValueLabel = new javax.swing.JLabel();
        civilStatusLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        genderValueLabel = new javax.swing.JLabel();
        civilStatusValueLabel = new javax.swing.JLabel();
        municipalityLabel = new javax.swing.JLabel();
        barangayLabel = new javax.swing.JLabel();
        registrationDateLabel = new javax.swing.JLabel();
        registrationDateValueLabel = new javax.swing.JLabel();
        municipalityValueLabel = new javax.swing.JLabel();
        barangayValueLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailValueLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordValueLabel = new javax.swing.JLabel();
        votersUpdateDetailsPanel = new javax.swing.JPanel();
        firstnameLabel1 = new javax.swing.JLabel();
        lastnameLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        ageLabel1 = new javax.swing.JLabel();
        genderLabel1 = new javax.swing.JLabel();
        civilStatusLabel1 = new javax.swing.JLabel();
        municipalityLabel1 = new javax.swing.JLabel();
        barangayLabel1 = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        voterPhotoDashboard1 = new javax.swing.JLabel();
        firstnameField = new CustomTextField.MyTextField();
        lastnameField = new CustomTextField.MyTextField();
        emailField = new CustomTextField.MyTextField();
        birthdateChooser = new com.toedter.calendar.JDateChooser();
        genderCombox = new javax.swing.JComboBox<>();
        statusCombox = new javax.swing.JComboBox<>();
        municipalityCombox = new javax.swing.JComboBox<>();
        barangayCombox = new javax.swing.JComboBox<>();
        passwordField = new CustomTextField.MyTextField();
        saveChangesButton = new javax.swing.JButton();
        votingStatusPanel = new javax.swing.JPanel();
        pieChart1 = new CustomChart.PieChart();
        votersMenuPanel = new javax.swing.JPanel();
        voteNowButton = new javax.swing.JButton();
        updateProfileButton = new javax.swing.JButton();
        votingStatusButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        myProfileButton = new javax.swing.JButton();

        castVotesDialog.setTitle("Voting System - Voter's Dashboard > Cast My Vote");
        castVotesDialog.setAlwaysOnTop(true);
        castVotesDialog.setResizable(false);
        castVotesDialog.setSize(new java.awt.Dimension(520, 745));

        castVotesPanel.setBackground(new java.awt.Color(28, 33, 32));
        castVotesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        castPresidentLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        castPresidentLabel.setForeground(new java.awt.Color(255, 255, 255));
        castPresidentLabel.setText("President");
        castVotesPanel.add(castPresidentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, 40));

        presidentCombox.setBackground(new java.awt.Color(71, 74, 73));
        presidentCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        presidentCombox.setForeground(new java.awt.Color(255, 255, 255));
        presidentCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        presidentCombox.setBorder(null);
        castVotesPanel.add(presidentCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 170, 40));

        castVicePresidentLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        castVicePresidentLabel.setForeground(new java.awt.Color(255, 255, 255));
        castVicePresidentLabel.setText("Vice President");
        castVotesPanel.add(castVicePresidentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 120, 40));

        castSecretaryLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        castSecretaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        castSecretaryLabel.setText("Secretary");
        castVotesPanel.add(castSecretaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, 40));

        castTreasurerLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        castTreasurerLabel.setForeground(new java.awt.Color(255, 255, 255));
        castTreasurerLabel.setText("Treasurer");
        castVotesPanel.add(castTreasurerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 120, 40));

        castPIOMale.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        castPIOMale.setForeground(new java.awt.Color(255, 255, 255));
        castPIOMale.setText("P.I.O.  (Male)");
        castVotesPanel.add(castPIOMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 120, 40));

        castAuditorLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        castAuditorLabel.setForeground(new java.awt.Color(255, 255, 255));
        castAuditorLabel.setText("Auditor");
        castVotesPanel.add(castAuditorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 120, 40));

        castPIOFemale.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        castPIOFemale.setForeground(new java.awt.Color(255, 255, 255));
        castPIOFemale.setText("P.I.O.  (Female)");
        castVotesPanel.add(castPIOFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 120, 40));

        castRepresentative.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        castRepresentative.setForeground(new java.awt.Color(255, 255, 255));
        castRepresentative.setText("Representative");
        castVotesPanel.add(castRepresentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 120, 40));

        vicePresidentCombox.setBackground(new java.awt.Color(71, 74, 73));
        vicePresidentCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        vicePresidentCombox.setForeground(new java.awt.Color(255, 255, 255));
        vicePresidentCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        vicePresidentCombox.setBorder(null);
        castVotesPanel.add(vicePresidentCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 170, 40));

        secretaryCombox.setBackground(new java.awt.Color(71, 74, 73));
        secretaryCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        secretaryCombox.setForeground(new java.awt.Color(255, 255, 255));
        secretaryCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        secretaryCombox.setBorder(null);
        castVotesPanel.add(secretaryCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 170, 40));

        treasurerCombox.setBackground(new java.awt.Color(71, 74, 73));
        treasurerCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        treasurerCombox.setForeground(new java.awt.Color(255, 255, 255));
        treasurerCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        treasurerCombox.setBorder(null);
        castVotesPanel.add(treasurerCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 170, 40));

        auditorCombox.setBackground(new java.awt.Color(71, 74, 73));
        auditorCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        auditorCombox.setForeground(new java.awt.Color(255, 255, 255));
        auditorCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        auditorCombox.setBorder(null);
        castVotesPanel.add(auditorCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 170, 40));

        pioMaleCombox.setBackground(new java.awt.Color(71, 74, 73));
        pioMaleCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        pioMaleCombox.setForeground(new java.awt.Color(255, 255, 255));
        pioMaleCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        pioMaleCombox.setBorder(null);
        castVotesPanel.add(pioMaleCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 170, 40));

        pioFemaleCombox.setBackground(new java.awt.Color(71, 74, 73));
        pioFemaleCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        pioFemaleCombox.setForeground(new java.awt.Color(255, 255, 255));
        pioFemaleCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        pioFemaleCombox.setBorder(null);
        castVotesPanel.add(pioFemaleCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 170, 40));

        representativeCombox.setBackground(new java.awt.Color(71, 74, 73));
        representativeCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        representativeCombox.setForeground(new java.awt.Color(255, 255, 255));
        representativeCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        representativeCombox.setBorder(null);
        castVotesPanel.add(representativeCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 170, 40));

        castMyVoteButton.setBackground(new java.awt.Color(255, 87, 87));
        castMyVoteButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        castMyVoteButton.setForeground(new java.awt.Color(255, 255, 255));
        castMyVoteButton.setText("Cast My Vote");
        castMyVoteButton.setBorder(null);
        castMyVoteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        castMyVoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castMyVoteButtonActionPerformed(evt);
            }
        });
        castVotesPanel.add(castMyVoteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 140, 45));

        clearFieldButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        clearFieldButton.setForeground(new java.awt.Color(51, 51, 51));
        clearFieldButton.setText("Clear Choices");
        clearFieldButton.setBorder(null);
        clearFieldButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldButtonActionPerformed(evt);
            }
        });
        castVotesPanel.add(clearFieldButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, 140, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/votinglogo2-medium.png"))); // NOI18N
        castVotesPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 50, 50));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VOTING SYSTEM");
        castVotesPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 50));

        javax.swing.GroupLayout castVotesDialogLayout = new javax.swing.GroupLayout(castVotesDialog.getContentPane());
        castVotesDialog.getContentPane().setLayout(castVotesDialogLayout);
        castVotesDialogLayout.setHorizontalGroup(
            castVotesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(castVotesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        castVotesDialogLayout.setVerticalGroup(
            castVotesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(castVotesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Voting System - Voter's Dashboard");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        votersMainPanel.setBackground(new java.awt.Color(28, 33, 32));
        votersMainPanel.setLayout(new java.awt.CardLayout());

        votersDetailsPanel.setBackground(new java.awt.Color(28, 33, 32));
        votersDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voterPhotoDashboard.setForeground(new java.awt.Color(255, 255, 255));
        voterPhotoDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar_200x200.png"))); // NOI18N
        votersDetailsPanel.add(voterPhotoDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 200, 200));

        votersIDLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        votersIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        votersIDLabel.setText("Voter's ID:");
        votersDetailsPanel.add(votersIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 80, 40));

        votersIDValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        votersIDValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        votersIDValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        votersIDValueLabel.setOpaque(true);
        votersDetailsPanel.add(votersIDValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 150, 40));

        firstnameLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        firstnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel.setText("First Name:");
        votersDetailsPanel.add(firstnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 170, 40));

        firstnameValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        firstnameValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        firstnameValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstnameValueLabel.setOpaque(true);
        votersDetailsPanel.add(firstnameValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 170, 40));

        lastnameValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        lastnameValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lastnameValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastnameValueLabel.setOpaque(true);
        votersDetailsPanel.add(lastnameValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 170, 40));

        ageLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age:");
        votersDetailsPanel.add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 170, 40));

        ageValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        ageValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        ageValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageValueLabel.setOpaque(true);
        votersDetailsPanel.add(ageValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 170, 40));

        civilStatusLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        civilStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        civilStatusLabel.setText("Civil Status:");
        votersDetailsPanel.add(civilStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 170, 40));

        genderLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender:");
        votersDetailsPanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 170, 40));

        genderValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        genderValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        genderValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderValueLabel.setOpaque(true);
        votersDetailsPanel.add(genderValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 170, 40));

        civilStatusValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        civilStatusValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        civilStatusValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        civilStatusValueLabel.setOpaque(true);
        votersDetailsPanel.add(civilStatusValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 170, 40));

        municipalityLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        municipalityLabel.setForeground(new java.awt.Color(255, 255, 255));
        municipalityLabel.setText("Municipality:");
        votersDetailsPanel.add(municipalityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 170, 40));

        barangayLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        barangayLabel.setForeground(new java.awt.Color(255, 255, 255));
        barangayLabel.setText("Barangay:");
        votersDetailsPanel.add(barangayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 170, 40));

        registrationDateLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        registrationDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        registrationDateLabel.setText("Registration Date: ");
        votersDetailsPanel.add(registrationDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 140, 40));

        registrationDateValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        registrationDateValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        registrationDateValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        registrationDateValueLabel.setOpaque(true);
        votersDetailsPanel.add(registrationDateValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 170, 40));

        municipalityValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        municipalityValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        municipalityValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        municipalityValueLabel.setOpaque(true);
        votersDetailsPanel.add(municipalityValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 170, 40));

        barangayValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        barangayValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        barangayValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        barangayValueLabel.setOpaque(true);
        votersDetailsPanel.add(barangayValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 170, 40));

        lastnameLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lastnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastnameLabel.setText("Last Name:");
        votersDetailsPanel.add(lastnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 170, 40));

        emailLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email:");
        votersDetailsPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 170, 40));

        emailValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        emailValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        emailValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailValueLabel.setOpaque(true);
        votersDetailsPanel.add(emailValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 170, 40));

        passwordLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");
        votersDetailsPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 170, 40));

        passwordValueLabel.setBackground(new java.awt.Color(71, 74, 73));
        passwordValueLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        passwordValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordValueLabel.setOpaque(true);
        votersDetailsPanel.add(passwordValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 170, 40));

        votersMainPanel.add(votersDetailsPanel, "card16");

        votersUpdateDetailsPanel.setBackground(new java.awt.Color(28, 33, 32));
        votersUpdateDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstnameLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        firstnameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel1.setText("First Name:");
        votersUpdateDetailsPanel.add(firstnameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 170, 40));

        lastnameLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lastnameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        lastnameLabel1.setText("Last Name:");
        votersUpdateDetailsPanel.add(lastnameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 170, 40));

        emailLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel1.setText("Email:");
        votersUpdateDetailsPanel.add(emailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 170, 40));

        ageLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ageLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel1.setText("Birthdate:");
        votersUpdateDetailsPanel.add(ageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 170, 40));

        genderLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        genderLabel1.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel1.setText("Gender:");
        votersUpdateDetailsPanel.add(genderLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 170, 40));

        civilStatusLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        civilStatusLabel1.setForeground(new java.awt.Color(255, 255, 255));
        civilStatusLabel1.setText("Civil Status:");
        votersUpdateDetailsPanel.add(civilStatusLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 170, 40));

        municipalityLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        municipalityLabel1.setForeground(new java.awt.Color(255, 255, 255));
        municipalityLabel1.setText("Municipality:");
        votersUpdateDetailsPanel.add(municipalityLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 170, 40));

        barangayLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        barangayLabel1.setForeground(new java.awt.Color(255, 255, 255));
        barangayLabel1.setText("Barangay:");
        votersUpdateDetailsPanel.add(barangayLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 170, 40));

        passwordLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        passwordLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel1.setText("Password:");
        votersUpdateDetailsPanel.add(passwordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 170, 40));

        voterPhotoDashboard1.setForeground(new java.awt.Color(255, 255, 255));
        voterPhotoDashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar_200x200.png"))); // NOI18N
        votersUpdateDetailsPanel.add(voterPhotoDashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 200, 200));

        firstnameField.setCaretColor(new java.awt.Color(255, 255, 255));
        firstnameField.setSelectedTextColor(new java.awt.Color(28, 33, 32));
        votersUpdateDetailsPanel.add(firstnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 170, -1));

        lastnameField.setCaretColor(new java.awt.Color(255, 255, 255));
        lastnameField.setSelectedTextColor(new java.awt.Color(28, 33, 32));
        votersUpdateDetailsPanel.add(lastnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 170, -1));

        emailField.setCaretColor(new java.awt.Color(255, 255, 255));
        emailField.setSelectedTextColor(new java.awt.Color(28, 33, 32));
        votersUpdateDetailsPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 170, -1));
        votersUpdateDetailsPanel.add(birthdateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 170, 40));

        genderCombox.setBackground(new java.awt.Color(71, 74, 73));
        genderCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        genderCombox.setForeground(new java.awt.Color(255, 255, 255));
        genderCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Male", "Female", "Non-Binary" }));
        genderCombox.setBorder(null);
        votersUpdateDetailsPanel.add(genderCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 170, 40));

        statusCombox.setBackground(new java.awt.Color(71, 74, 73));
        statusCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        statusCombox.setForeground(new java.awt.Color(255, 255, 255));
        statusCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Single", "Married", "Divorced", "Separated", "Widowed" }));
        statusCombox.setBorder(null);
        votersUpdateDetailsPanel.add(statusCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 170, 40));

        municipalityCombox.setBackground(new java.awt.Color(71, 74, 73));
        municipalityCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        municipalityCombox.setForeground(new java.awt.Color(255, 255, 255));
        municipalityCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Agdangan", "Padre Burgos", "Unisan" }));
        municipalityCombox.setBorder(null);
        municipalityCombox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                municipalityComboxItemStateChanged(evt);
            }
        });
        votersUpdateDetailsPanel.add(municipalityCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 170, 40));

        barangayCombox.setBackground(new java.awt.Color(71, 74, 73));
        barangayCombox.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        barangayCombox.setForeground(new java.awt.Color(255, 255, 255));
        barangayCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        barangayCombox.setBorder(null);
        votersUpdateDetailsPanel.add(barangayCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 170, 40));

        passwordField.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordField.setSelectedTextColor(new java.awt.Color(28, 33, 32));
        votersUpdateDetailsPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 170, 40));

        saveChangesButton.setBackground(new java.awt.Color(255, 103, 103));
        saveChangesButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        saveChangesButton.setForeground(new java.awt.Color(255, 255, 255));
        saveChangesButton.setText("Save Changes");
        saveChangesButton.setBorder(null);
        saveChangesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });
        votersUpdateDetailsPanel.add(saveChangesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 170, 40));

        votersMainPanel.add(votersUpdateDetailsPanel, "card3");

        votingStatusPanel.setBackground(new java.awt.Color(28, 33, 32));
        votingStatusPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        votingStatusPanel.add(pieChart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 400, 310));

        votersMainPanel.add(votingStatusPanel, "card4");

        getContentPane().add(votersMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 420));
        votersMainPanel.getAccessibleContext().setAccessibleName("Voter's Card");

        votersMenuPanel.setBackground(new java.awt.Color(255, 103, 103));
        votersMenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voteNowButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        voteNowButton.setForeground(new java.awt.Color(28, 33, 32));
        voteNowButton.setText("Vote Now");
        voteNowButton.setBorder(null);
        voteNowButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voteNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteNowButtonActionPerformed(evt);
            }
        });
        votersMenuPanel.add(voteNowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 140, 30));

        updateProfileButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        updateProfileButton.setForeground(new java.awt.Color(28, 33, 32));
        updateProfileButton.setText("Update Profile");
        updateProfileButton.setBorder(null);
        updateProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileButtonActionPerformed(evt);
            }
        });
        votersMenuPanel.add(updateProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 30));

        votingStatusButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        votingStatusButton.setForeground(new java.awt.Color(28, 33, 32));
        votingStatusButton.setText("Voting Status");
        votingStatusButton.setBorder(null);
        votingStatusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        votingStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votingStatusButtonActionPerformed(evt);
            }
        });
        votersMenuPanel.add(votingStatusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 130, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/votinglogo2-white-smallpng.png"))); // NOI18N
        votersMenuPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VOTING SYSTEM");
        votersMenuPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 180, 50));

        myProfileButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        myProfileButton.setForeground(new java.awt.Color(28, 33, 32));
        myProfileButton.setText("My Profile");
        myProfileButton.setBorder(null);
        myProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileButtonActionPerformed(evt);
            }
        });
        votersMenuPanel.add(myProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 140, 30));

        getContentPane().add(votersMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 940, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voteNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteNowButtonActionPerformed
        // TODO add your handling code here:
        castVotesDialog.setLocationRelativeTo(votersMainPanel);
        castVotesDialog.setVisible(true);
        
    }//GEN-LAST:event_voteNowButtonActionPerformed

    private void castMyVoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castMyVoteButtonActionPerformed
        // TODO add your handling code here:
        
        // Create and Assign values into VoteTransferObject List
        CandidateAccessObject candidateAccessObj = new CandidateAccessObject();
        
        int selectedPresident = candidateAccessObj.getCandidateId(presidentCombox.getSelectedItem().toString());
        int selectedVicePresident = candidateAccessObj.getCandidateId(vicePresidentCombox.getSelectedItem().toString());
        int selectedSecretary = candidateAccessObj.getCandidateId(secretaryCombox.getSelectedItem().toString());
        int selectedTreasurer = candidateAccessObj.getCandidateId(treasurerCombox.getSelectedItem().toString());
        int selectedAuditor =candidateAccessObj.getCandidateId( auditorCombox.getSelectedItem().toString());
        int selectedPIOMale = candidateAccessObj.getCandidateId(pioMaleCombox.getSelectedItem().toString());
        int selectedPIOFemale = candidateAccessObj.getCandidateId(pioFemaleCombox.getSelectedItem().toString());
        int selectedRepresentative = candidateAccessObj.getCandidateId(representativeCombox.getSelectedItem().toString());
        List<VoteTransferObject> votes = new ArrayList<>();
        int[] selectedCandidates = {selectedPresident, selectedVicePresident, selectedSecretary, selectedTreasurer, selectedAuditor, selectedPIOMale, selectedPIOFemale, selectedRepresentative};
        int ctr = 1;
        for(int selectedCandidate : selectedCandidates){
            VoteTransferObject vote = new VoteTransferObject(ctr, user.getUserID(), selectedCandidate);
            ctr++;
            votes.add(vote);
        }
        
        VoteAccessObject voteAccessObject = new VoteAccessObject();
        if(voteAccessObject.castVote(votes)){
            JOptionPane.showMessageDialog(castVotesDialog, "Vote casted successfully!", "Success!", JOptionPane.INFORMATION_MESSAGE);
            String defaultValue = "Default";
            presidentCombox.setSelectedItem(defaultValue);
            vicePresidentCombox.setSelectedItem(defaultValue);
            secretaryCombox.setSelectedItem(defaultValue);
            treasurerCombox.setSelectedItem(defaultValue);
            auditorCombox.setSelectedItem(defaultValue);
            pioMaleCombox.setSelectedItem(defaultValue);
            pioFemaleCombox.setSelectedItem(defaultValue);
            representativeCombox.setSelectedItem(defaultValue);
            castVotesDialog.setVisible(false);
            voteNowButton.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(castVotesDialog, "Something went wrong!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_castMyVoteButtonActionPerformed

    private void clearFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldButtonActionPerformed
        
        // Assigning Default value in each ComboBox
        String defaultValue = "Default";
        presidentCombox.setSelectedItem(defaultValue);
        vicePresidentCombox.setSelectedItem(defaultValue);
        secretaryCombox.setSelectedItem(defaultValue);
        treasurerCombox.setSelectedItem(defaultValue);
        auditorCombox.setSelectedItem(defaultValue);
        pioMaleCombox.setSelectedItem(defaultValue);
        pioFemaleCombox.setSelectedItem(defaultValue);
        representativeCombox.setSelectedItem(defaultValue);
        
    }//GEN-LAST:event_clearFieldButtonActionPerformed

    private void votingStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votingStatusButtonActionPerformed
        votersMainPanel.removeAll();
        votersMainPanel.add(votingStatusPanel);
        votersMainPanel.repaint();
        votersMainPanel.revalidate();
        
    }//GEN-LAST:event_votingStatusButtonActionPerformed

    private void myProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileButtonActionPerformed
        votersMainPanel.removeAll();
        votersMainPanel.add(votersDetailsPanel);
        votersMainPanel.repaint();
        votersMainPanel.revalidate();
    }//GEN-LAST:event_myProfileButtonActionPerformed

    private void updateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileButtonActionPerformed
        
        UserAccessObject updateAccessObject = new UserAccessObject();
        UserTransferObject freshData = updateAccessObject.getAllUserData(emailValueLabel.getText(), passwordValueLabel.getText());
        
        firstnameField.setText(freshData.getFirstname());
        lastnameField.setText(freshData.getLastname());
        emailField.setText(freshData.getEmail());
        birthdateChooser.setDate(freshData.getBirthDate());
        genderCombox.setSelectedItem(freshData.getGender());
        statusCombox.setSelectedItem(freshData.getStatus());
        municipalityCombox.setSelectedItem(freshData.getMunicipality());
        
        // Populate barangays in JComboBox
        barangayCombox.removeAllItems();
        LocationHandler locationHandler = new LocationHandler();
        if (municipalityCombox.getSelectedItem().equals("Default")) {
            barangayCombox.addItem("Default");
        } else if(municipalityCombox.getSelectedItem().equals("Agdangan")){
            for (String barangayLocation : locationHandler.getAgdanganBarangay()) {
                barangayCombox.addItem(barangayLocation);
            }
        } else if (municipalityCombox.getSelectedItem().equals("Unisan")) {
            for (String barangayLocation : locationHandler.getUnisanBarangay()) {
                barangayCombox.addItem(barangayLocation);
            }
        } else if (municipalityCombox.getSelectedItem().equals("Padre Burgos")) {
            for (String barangayLocation : locationHandler.getPadreBurgosBarangay()) {
                barangayCombox.addItem(barangayLocation);
            }
        }
        
        barangayCombox.setSelectedItem(freshData.getBarangay());
        passwordField.setText(freshData.getPassword());
        
        votersMainPanel.removeAll();
        votersMainPanel.add(votersUpdateDetailsPanel);
        votersMainPanel.repaint();
        votersMainPanel.revalidate();
        
    }//GEN-LAST:event_updateProfileButtonActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        UserAccessObject userAccessObject = new UserAccessObject();
        UserTransferObject updatedData = new UserTransferObject();
        
        // Check for empty fields
        if (firstnameField.getText().isEmpty() ||
            lastnameField.getText().isEmpty() ||
            emailField.getText().isEmpty() ||
            birthdateChooser.getDate() == null ||
            genderCombox.getSelectedItem().equals("Default") ||
            statusCombox.getSelectedItem().equals("Default") ||
            municipalityCombox.getSelectedItem().equals("Default") ||
            barangayCombox.getSelectedItem().equals("Default") ||
            passwordField.getText().isEmpty() ) {
            
            JOptionPane.showMessageDialog(votersMainPanel, "Seems like you were checking if we will ignore empty fields.", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            if (firstnameField.getText().equals(user.getFirstname()) &&
                lastnameField.getText().equals(user.getLastname()) && 
                emailField.getText().equals(user.getEmail()) &&
                new java.sql.Date( birthdateChooser.getDate().getTime()).equals(user.getBirthDate()) &&
                genderCombox.getSelectedItem().toString().equals(user.getGender()) &&
                statusCombox.getSelectedItem().toString().equals(user.getStatus()) &&
                municipalityCombox.getSelectedItem().toString().equals(user.getMunicipality()) &&
                barangayCombox.getSelectedItem().toString().equals(user.getBarangay()) &&
                passwordField.getText().equals(user.getPassword())) {
                JOptionPane.showMessageDialog(votersMainPanel, "No changes have been made.", "Notice!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                java.util.Date birthdate = birthdateChooser.getDate();
                updatedData.setFirstname(firstnameField.getText());
                updatedData.setLastname(lastnameField.getText());
                updatedData.setEmail(emailField.getText());
                updatedData.setBirthDate(new java.sql.Date(birthdate.getTime()));
                updatedData.setGender(genderCombox.getSelectedItem().toString());
                updatedData.setStatus(statusCombox.getSelectedItem().toString());
                updatedData.setMunicipality(municipalityCombox.getSelectedItem().toString());
                updatedData.setBarangay(barangayCombox.getSelectedItem().toString());
                updatedData.setRole("voter");
                updatedData.setPassword(passwordField.getText());
                
                userAccessObject.updateUser(updatedData);
                
                JOptionPane.showMessageDialog(votersMainPanel, "Your details have been updated successfully!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                
                votersIDValueLabel.setText(String.valueOf(updatedData.getUserID()));
                registrationDateValueLabel.setText(String.valueOf(updatedData.getRegistrationDate()));
                firstnameValueLabel.setText(updatedData.getFirstname());
                lastnameValueLabel.setText(updatedData.getLastname());
                emailValueLabel.setText(updatedData.getEmail());
                ageValueLabel.setText(String.valueOf(computeAge(updatedData)));
                genderValueLabel.setText(user.getGender());
                civilStatusValueLabel.setText(user.getStatus());
                municipalityValueLabel.setText(user.getMunicipality());
                barangayValueLabel.setText(user.getBarangay());
                passwordValueLabel.setText(user.getPassword());
            }
        }
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void municipalityComboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_municipalityComboxItemStateChanged
        barangayCombox.removeAllItems();
        LocationHandler locationHandler = new LocationHandler();
        if (municipalityCombox.getSelectedItem().equals("Default")) {
            barangayCombox.addItem("Default");
        } else if(municipalityCombox.getSelectedItem().equals("Agdangan")){
            for (String barangayLocation : locationHandler.getAgdanganBarangay()) {
                barangayCombox.addItem(barangayLocation);
            }
        } else if (municipalityCombox.getSelectedItem().equals("Unisan")) {
            for (String barangaLocation : locationHandler.getUnisanBarangay()) {
                barangayCombox.addItem(barangaLocation);
            }
        } else if (municipalityCombox.getSelectedItem().equals("Padre Burgos")) {
            for (String barangaLocation : locationHandler.getPadreBurgosBarangay()) {
                barangayCombox.addItem(barangaLocation);
            }
        }
    }//GEN-LAST:event_municipalityComboxItemStateChanged

    public int computeAge(UserTransferObject user){
        // Get age
        Calendar currentDate = Calendar.getInstance();

        // Get the selected date
        Calendar selectedCalendar = Calendar.getInstance();
        selectedCalendar.setTime(user.getBirthDate());

        // Calculate the age
        int age = currentDate.get(Calendar.YEAR) - selectedCalendar.get(Calendar.YEAR);
        if (currentDate.get(Calendar.DAY_OF_YEAR) < selectedCalendar.get(Calendar.DAY_OF_YEAR)) {
            age--;
        }
        return age;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VoterDashboard(user).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageLabel1;
    private javax.swing.JLabel ageValueLabel;
    private javax.swing.JComboBox<String> auditorCombox;
    private javax.swing.JComboBox<String> barangayCombox;
    private javax.swing.JLabel barangayLabel;
    private javax.swing.JLabel barangayLabel1;
    private javax.swing.JLabel barangayValueLabel;
    private com.toedter.calendar.JDateChooser birthdateChooser;
    private javax.swing.JLabel castAuditorLabel;
    private javax.swing.JButton castMyVoteButton;
    private javax.swing.JLabel castPIOFemale;
    private javax.swing.JLabel castPIOMale;
    private javax.swing.JLabel castPresidentLabel;
    private javax.swing.JLabel castRepresentative;
    private javax.swing.JLabel castSecretaryLabel;
    private javax.swing.JLabel castTreasurerLabel;
    private javax.swing.JLabel castVicePresidentLabel;
    private javax.swing.JDialog castVotesDialog;
    private javax.swing.JPanel castVotesPanel;
    private javax.swing.JLabel civilStatusLabel;
    private javax.swing.JLabel civilStatusLabel1;
    private javax.swing.JLabel civilStatusValueLabel;
    private javax.swing.JButton clearFieldButton;
    private CustomTextField.MyTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailValueLabel;
    private CustomTextField.MyTextField firstnameField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JLabel firstnameLabel1;
    private javax.swing.JLabel firstnameValueLabel;
    private javax.swing.JComboBox<String> genderCombox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JLabel genderValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private CustomTextField.MyTextField lastnameField;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JLabel lastnameLabel1;
    private javax.swing.JLabel lastnameValueLabel;
    private javax.swing.JComboBox<String> municipalityCombox;
    private javax.swing.JLabel municipalityLabel;
    private javax.swing.JLabel municipalityLabel1;
    private javax.swing.JLabel municipalityValueLabel;
    private javax.swing.JButton myProfileButton;
    private CustomTextField.MyTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLabel passwordValueLabel;
    private CustomChart.PieChart pieChart1;
    private javax.swing.JComboBox<String> pioFemaleCombox;
    private javax.swing.JComboBox<String> pioMaleCombox;
    private javax.swing.JComboBox<String> presidentCombox;
    private javax.swing.JLabel registrationDateLabel;
    private javax.swing.JLabel registrationDateValueLabel;
    private javax.swing.JComboBox<String> representativeCombox;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JComboBox<String> secretaryCombox;
    private javax.swing.JComboBox<String> statusCombox;
    private javax.swing.JComboBox<String> treasurerCombox;
    private javax.swing.JButton updateProfileButton;
    private javax.swing.JComboBox<String> vicePresidentCombox;
    private javax.swing.JButton voteNowButton;
    private javax.swing.JLabel voterPhotoDashboard;
    private javax.swing.JLabel voterPhotoDashboard1;
    private javax.swing.JPanel votersDetailsPanel;
    private javax.swing.JLabel votersIDLabel;
    private javax.swing.JLabel votersIDValueLabel;
    private javax.swing.JPanel votersMainPanel;
    private javax.swing.JPanel votersMenuPanel;
    private javax.swing.JPanel votersUpdateDetailsPanel;
    private javax.swing.JButton votingStatusButton;
    private javax.swing.JPanel votingStatusPanel;
    // End of variables declaration//GEN-END:variables
}
